/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DIOparallel;

public class App {

    public static void main(String[] args) {
        System.out.println("Training Parallel process.");

        try {

            long initialTime = System.currentTimeMillis();
            int n = 2000000000;
            FunctionN firstThread = new FunctionN(n);
            FunctionNsquare secondThread = new FunctionNsquare(n);

            Thread justN = new Thread(firstThread);
            Thread nSquare = new Thread(secondThread);

            nSquare.start();            
            justN.start();

            boolean checkN = false;
            boolean checkNSquare = false;
            while(true) {
                if (!justN.isAlive() && !checkN) {
                    System.out.println("O(n) = n has finished in "+ (System.currentTimeMillis() - initialTime) +" miliseconds.");
                    checkN = true;
                }
                if (!nSquare.isAlive() && !checkNSquare) {
                    System.out.println("O(n) = n^2 has finished in "+ (System.currentTimeMillis() - initialTime) +" miliseconds.");
                    checkNSquare = true;
                }

                if(!justN.isAlive() && !nSquare.isAlive()) {
                    break;
                }
            }
        }
        catch (Exception e) {
            System.out.println("Unable to start threading");
        }

    }
}