/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DIOparallel;

public class App {

    public static void main(String[] args) {
        System.out.println("Training Parallel process.");

        try {

            int n = 2000000000;
            FunctionN firstThread = new FunctionN(n);
            FunctionNsquare secondThread = new FunctionNsquare(n);

            Thread justN = new Thread(firstThread);
            Thread nSquare = new Thread(secondThread);

            nSquare.start();            
            justN.start();

            while(true) {
                if (justN.isInterrupted()) {
                    throw new InterruptedException();
                }
                if (nSquare.isInterrupted()) {
                    throw new InterruptedException();
                }

                if(!justN.isAlive() && !nSquare.isAlive()) {
                    break;
                }
            }
        }
        catch (Exception e) {
            System.out.println("Unable to start threading");
        }

    }
}