/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DIOTestProject;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    private final App tester = new App();

    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    void exponentialTestPowerByOne() {
        assertEquals(2, tester.power(2, 1));
    }
    
    @Test
    void exponentialTestPowerByZero() {
        assertEquals(1, tester.power(2, 0));
    }
    
    @Test
    void exponentialTestPowerByTwo() {
        assertEquals(4, tester.power(2, 2));
    }

    
    @Test
    void getStringTestPlayPlay() {
        assertEquals("PlayPlay", tester.getString("PlayPlay"));
    }
    
    @Test
    void getStringTestNoString() {
        assertEquals("", tester.getString(""));
    }

    @Test
    void getGreetingTest() {
        assertEquals("Hello World!", tester.getGreeting());
    }
}
